import { ReleaseSession } from '../types/releaseMode';

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function formatDuration(startedAt: string, endedAt: string): string {
  const ms = new Date(endedAt).getTime() - new Date(startedAt).getTime();
  const totalMinutes = Math.floor(ms / 60000);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m`;
}

/**
 * Build an HTML description for an ADO Release work item
 * from a completed ReleaseSession.
 */
export function buildReleaseDescription(session: ReleaseSession): string {
  const lines: string[] = [];

  const endedAt = session.endedAt || new Date().toISOString();

  lines.push(`<h3>${esc(session.name)}</h3>`);
  lines.push(`<table>`);
  lines.push(`  <tr><td><b>Started by</b></td><td>${esc(session.startedBy.displayName)}</td></tr>`);
  lines.push(`  <tr><td><b>Started at</b></td><td>${new Date(session.startedAt).toLocaleString()}</td></tr>`);
  lines.push(`  <tr><td><b>Ended at</b></td><td>${new Date(endedAt).toLocaleString()}</td></tr>`);
  lines.push(`  <tr><td><b>Duration</b></td><td>${formatDuration(session.startedAt, endedAt)}</td></tr>`);
  lines.push(`</table>`);

  // Summary counts
  const approvals = session.actions.filter(a => a.action === 'approve').length;
  const rejections = session.actions.filter(a => a.action === 'reject').length;
  const succeeded = session.actions.filter(a => a.stageOutcome === 'succeeded').length;
  const failed = session.actions.filter(a => a.stageOutcome === 'failed').length;

  lines.push(`<p>`);
  lines.push(`  <b>Approvals:</b> ${approvals} &nbsp; <b>Rejections:</b> ${rejections} &nbsp; `);
  lines.push(`  <b>Stages succeeded:</b> ${succeeded} &nbsp; <b>Stages failed:</b> ${failed}`);
  lines.push(`</p>`);

  // Pipeline runs
  const seenPipelines = new Set<string>();
  const pipelineEntries: { name: string; url?: string }[] = [];
  for (const a of session.actions) {
    const key = a.pipelineUrl || a.pipelineName;
    if (!seenPipelines.has(key)) {
      seenPipelines.add(key);
      pipelineEntries.push({ name: a.pipelineName, url: a.pipelineUrl });
    }
  }

  if (pipelineEntries.length > 0) {
    lines.push(`<p><b>Pipeline Runs (${pipelineEntries.length})</b></p><ul>`);
    for (const p of pipelineEntries) {
      if (p.url) {
        lines.push(`  <li><a href="${esc(p.url)}">${esc(p.name)}</a></li>`);
      } else {
        lines.push(`  <li>${esc(p.name)}</li>`);
      }
    }
    lines.push(`</ul>`);
  }

  // Work items (grouped by type, deduped)
  const wiMap = new Map<string, { id: number; title: string; type: string }[]>();
  for (const a of session.actions) {
    for (const wi of a.workItemRefs || []) {
      const list = wiMap.get(wi.type) || [];
      if (!list.some(x => x.id === wi.id)) {
        list.push({ id: wi.id, title: wi.title, type: wi.type });
      }
      wiMap.set(wi.type, list);
    }
  }

  if (wiMap.size > 0) {
    const typeOrder = ['Epic', 'Feature', 'User Story', 'Bug', 'Task'];
    const sortedTypes = [
      ...typeOrder.filter(t => wiMap.has(t)),
      ...[...wiMap.keys()].filter(t => !typeOrder.includes(t)),
    ];

    lines.push(`<p><b>Work Items</b></p>`);
    for (const type of sortedTypes) {
      const items = wiMap.get(type)!;
      lines.push(`<p><i>${esc(type)} (${items.length})</i></p><ul>`);
      for (const item of items) {
        lines.push(`  <li>#${item.id} ${esc(item.title)}</li>`);
      }
      lines.push(`</ul>`);
    }
  }

  // Notes
  if (session.notes && session.notes.length > 0) {
    lines.push(`<p><b>Notes</b></p><ul>`);
    for (const note of session.notes) {
      lines.push(`  <li>${esc(note.text)} <i>(${esc(note.author)}, ${new Date(note.timestamp).toLocaleString()})</i></li>`);
    }
    lines.push(`</ul>`);
  }

  lines.push(`<hr/><p><i>Generated by Release Hub</i></p>`);

  return lines.join('\n');
}
